import type { NextPage } from "next";
import Main from "../components/main/Main";
import Head from "next/head";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Aviato.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex pt-16 bg-gray-500 w-full justify-center">
          <div className="bg-violet-500">left</div>
          <div className="bg-violet-500">center</div>
          <div className="bg-violet-500">right</div>
        </div>
      </main>
    </div>
  );
};

export default Home;
