import type { NextPage } from "next";
import Main from "../components/main/Main";
import Head from "next/head";
import Sidebar from "../components/sidebar/Sidebar"
import Right from "../components/right/Right"
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Aviato.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex bg-gray-500 w-full justify-center">
          <div className="flex bg-violet-500 h-screen sticky top-16 items-center" >
          <div className=""><Sidebar /></div>
          </div>
          <div className="bg-violet-500 my-16"><Main /><Main /><Main /><Main /><Main /></div>
          <div className="flex bg-violet-500 h-screen sticky top-16 items-start"><Right /></div>
        </div>
      </main>
    </div>
  );
};

export default Home;
